---
title: "ST5222- notes + assessment code"
author: "Zhu Xu"
date: "2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
 

```{r}
n <- 1000 #obtain 1000 samples
x <- c(1:n) #vector to store samples
acc <- 0 #obtain the acceptance rate
m <- 2*exp(-0.5) #precompute M
for (i in 1:n) #main loop to obtain samples
  {
  acc1 <- 0 #local acceptance rate
  j <- 0
  while (j==0)  #do reject
    {
    u1 <- runif(1,0,1) #generate a uniform [0,1] r.v
    y <- tan(pi*(u1-0.5)) #generate proposal
    acc1 <- acc1 +1 #count proposal value
    rat <- (exp(-0.5*y*y)/(m))*(1+y*y) #calculate acceptance prob
    u2 <- runif(1,0,1)
    if(u2<rat)
    {
      x[i] <- y #accept
      j <- 1 # jump out of while loop 
    }
  }
  acc <- acc + acc1 #record acceptance rate
}
acc <- acc/n
acc #display acceptance rate
hist(x,freq = F, ncalss = 100) #display histogram of accepted samples
```

```{r}
n <- 1000
x <- matrix(0,n,2)
mu <- c(1,1)
sigma <- matrix(0,2,2)
sigma[1,1] <- 1
sigma[2,2] <- 1
sigma[2,1] <- 0
sigma[1,2] <- sigma[2,1]
x[1,1] <- rnorm(1,0,1)
x[1,2] <- rnorm(1,0,1)
me <- 1
var1 <- sqrt(sigma[1,1] - sigma[1,2]*sigma[1,2]/sigma[2,2])
var2 <- sqrt(sigma[2,2] - sigma[1,2]*sigma[1,2]/sigma[1,1])
for(i in 2:n)
{
  me <- mu[1] + sigma[1,2]/sigma[2,2]*(x[i-1,2]-mu[2])
  x[i,1] <- rnorm(1,me,var1)
  me <- mu[2] + sigma[1,2]/sigma[1,1]*(x[i,1]-mu[1])
  x[i,2] <- rnorm(1,me,var2)
}
par(mfrow=c(2,1))
plot(x[,1], type = "l", xlab = "iteration")
plot(x[,2], type = "l", xlab = "iteration")
plot(acf(x[,1], lag = 50))
plot(acf(x[,2], lag = 50))
plot(x[,1],x[,2])
```

```{r}
lambda <- 50
f_1 <- function(x){(factorial(100)/(factorial(x)*factorial(100-x)))*0.5^(x)*(1-0.5)^(100-x)} 
#定义目标分布，n重伯努利分布,n=100,p=0.5
q_1 <- function(x){((lambda^x)*exp(-lambda))/factorial(x)} 
#定义proposal function q_1 , lambda=np=50的泊松分布
n <- 100 
X <- numeric() #存储抽样值
count <- 1 #X中的抽样值顺序
x_old <- 0 #初始化x_old
for(i in 1:10000)
{
 
  x_new <- rpois(1, lambda)#从lambda=np=50的泊松分布里抽取一个样本候选值
  u <- runif(1,0,1) #从均匀分布[0,1]中抽取一个值
  acc_1 <- min((f_1(x_new)*q_1(x_old))/(f_1(x_old)*q_1(x_new)), 1) #计算当前的接受概率
  if(u < acc_1) #判定是否接受，若接受就将x_new的值作为成功抽样存储到X中
  {
    X[count] <- x_new
    count <- count +1
    x_old <- x_new
  }
  else #若不接受，则重新循环，重新抽取x_new,检测是否满足抽样接受条件
  {
    x_old <- x_old
  }
}
par(mfrow = c(2, 2), mar = c(4, 4, 1, 1))
hist(X)
XX <- rbinom(10000, 100, 0.5) 
hist(XX)
P <- density(X, n = 10000, from = 1, to  = 100)
plot(P)
B <- density(XX, n = 10000, from = 1, to  = 100)
plot(B)

p <- 0.5
real <- rbinom(10000, 100, p)
right_boundary <- max( c( (median(real)-1)*2.5, (median(X)-1)*2.5) )
  if(right_boundary > 100){right_boundary <- 100}


  d <- density(real, n = 10000, from = 1, to = right_boundary)
  d1 <- density(X, n = 10000, from = 1, to = right_boundary)
  Data_up <- data.frame(count = d$x, y = d$y, legend = rep(c("Binomial Samples"), 10000, 1))
  Data_down <- data.frame(count = d1$x, y = d1$y, legend = rep(c("MH Samples"), 10000, 1))
  Data <- rbind(Data_up, Data_down)
  acceptance_rate <- (count-1) / 100000
  library(ggplot2)
  g <- ggplot( Data, aes(x = count, y = y, group = legend) ) + 
    geom_line( aes(color = legend), size = 0.5 ) +
    xlab("Count") + ylab("Frequency") + 
    scale_color_manual(values = c("black", "blue")) + 
    theme(panel.background = element_rect(fill = 'white', colour = 'black'))
  g
```
