---
title: "Tut7_ST5218"
author: 
- Name:Zhu Xu
- User ID:E0337988
- Matriculation ID:A0191344H
date: "3/April/2019"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
\rule[-5pt]{16.3cm}{0.15em}
\linespread{1.3}

###Question 1:

```{r}
library(tseries)
library(timeSeries)
P = get.hist.quote(instrument = "^DJI",
                  start="2001-01-01",end="2010-12-31",
                  quote = c("AdjClose"),
                  provider ="yahoo", 
                  compression = "m") 
r = diff(data.matrix(log(P))) 
acf(r)
```

###Question 2:

####a)

For all t

$$
E(Z_t)=E(X)=\mu,\qquad \gamma(t+h,t)=\frac{cov(Z_{t+h},Z_t)}{cov(Z_t)}=\frac{cov(X,X)}{cov(X)}=1
$$

Thus $\{Z_t\}$ is weakly stationary.

####b)

According to (a), the covariance is a constant 1.

###Question 3:

####a)

Since $\{X_t\}$ is a zero-mean series

$$
E(Z_t)=5+2t+E(X_t)=5=2t
$$

\newpage
####b)

$$
\gamma(Z_t)=cov(Z_{t+h},Z_t)=cov(X_{t+h},X_t)=\gamma_X(h)
$$

####c)

$Z_t$ is not stationary because its expectation is dependent on t.

###Question 4:

$$
E(X_h)=E(U_t)+E(V_t)=\mu_U+\mu_V
$$

$$
\Rightarrow\quad \gamma_X(t+h,t)=\frac{X_{t+h},X_t}{cov(X_t)}=\frac{\gamma_U(h)\gamma_U(0)+\gamma_V(h)\gamma_V(0)}{\gamma_U(0)\gamma_V(0)}=\gamma_X(h)=\gamma_X(-h)
$$

Thus both of them are independent with t, the time series is weakly stationary.

\newpage
###Question 5:

####a)

```{r}
P = get.hist.quote(instrument = "Goog",
                  start="2001-01-01",
                  end="2014-12-31", 
                  quote = c("AdjClose"),
                  provider = "yahoo", 
                  compression = "m")
plot(P, type='l', ylab='daily price', xlab='year')
```

####b)

```{r}
acf(as.timeSeries(P))
```

####c)

```{r}
Z = as.timeSeries(diff(P))
plot(Z, type='l', ylab='daily revenue', xlab='year')
```

####d)

```{r}
acf(Z)
```

####e)

```{r}
Box.test(Z, lag=20, type="Ljung")
Box.test(Z^2, lag=20, type="Ljung")
```



