---
title: "ST5207"
author: "Zhu Xu"
date: "2019/9/8"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# ST5207 R Code

```{r}
n=1000;
ex=2;
if (ex==1){x=rnorm(n)}
if (ex==2){x=rexp(n)}
if (ex==3){x=runif(n)}

par(mfrow=c(3,1))

hist(x, main=('Histogram: default number of bins'));

m=floor(1+log2(n));
hist(x,breaks=m,main=paste('#Bins selected by Sturges (1926)=',m,'\n'))

gamma3=mean((x-mean(x))^3)/sd(x)^3  ## standardized sknewness
m=floor(log2(1+gamma3*sqrt(n/6)));
hist(x,breaks=m,main=paste('#Bins selected by Doane (1926)=',m,'\n'))
```

## Lecture 3 - KDE

> Usage  density(x, ...)
'''
Default S3 method:
density(x, bw = "nrd0", adjust = 1,
        kernel = c("gaussian", "epanechnikov", "rectangular",
                   "triangular", "biweight",
                   "cosine", "optcosine"),
       weights = NULL, window = kernel, width,
       give.Rkern = FALSE,
       n = 512, from, to, cut = 3, na.rm = FALSE, ...)
'''


### Using Different Kernels
```{r}
n=200
x = rnorm(n)
par(mfrow = c(2,2))

# Uniform Kernel
xkde = density(x, kernel='rectangular')
plot(xkde)

# Normal Kernel
xkde = density(x, kernel='gaussian')
plot(xkde)

# Optimal Kernel
xkde = density(x, kernel='epanechnikov')
plot(xkde)

# Biweight Kernel
xkde = density(x, kernel='biweight')
plot(xkde)
```


## Using Different Bandwidth h
```{r}
n = 200

x=rnorm(n)
par(mfrow=c(3,1))

# Default Bandwidth
xkde = density(x, kernel='gaussian')
h = xkde$bw
plot(xkde)

# Too Small Bandwidth
xkde = density(x, kernel='gaussian', bw=h/3)
plot(xkde)

# Too Big Bandwidth
xkde = density(x, kernel='gaussian', bw=h*3)
plot(xkde)
```


## Lecture 4 - Bandwidth Selection
```{r}
# Normal Reference Bandwidth

n = 200
x = rnorm(n)
par(mfrow=c(2,2))

## Default Bandwidth
xkde = density(x, kernel='gaussian')
h = xkde$bw
plot(xkde, main='Gaussian xkde$bw')

hsig = sd(x)
rhsig = min(c(hsig, (quantile(x, 0.75)-quantile(x, 0.25))/1.34))

### Using Gaussian Kernel
# R(k)=\frac{1}{2*\sqrt{\pi}}, \sigma_K^2 = 1
href = 1.06*rhsig*n^(-1/5)
xkde = density(x, kernel='gaussian', bw=href)
plot(xkde, main='Gaussian')


### Using Uniform Kernel
RK = 1/10
sigK = sqrt(1/3)
const = (RK/sigK^4 * 8*sqrt(pi)/3)^(1/5)
const # = 1.335849

href=const*rhsig*n^(-1/5)
xkde = density(x, kernel='rectangular', bw=href)
plot(xkde, main='Uniform')

### Using Optimal Kernel
RK = 3/5
sigK = sqrt(1/5)
const = (RK/sigK^4 * 8*sqrt(pi)/3)^(1/5)
const # = 2.344914

href=const*rhsig*n^(-1/5)
xkde = density(x, kernel='rectangular', bw=href)
plot(xkde, main='Optimal')
```


## Lecture 5
```{r}


```


## Tut-4 CI
```{r}
data = read.table('/Users/xuzhu/Desktop/Notes/Sem3/ST5207-Nonparametric_Regression/Tut/cdrate.dat', header=FALSE)
names(data) = c('CD_rates', 'Indicator')
group_1 = data[which(data[,2]==0), ]
group_2 = data[which(data[,2]==1), ]

list_1 = group_1$CD_rates
list_2 = group_2$CD_rates
list_3 = data$CD_rates

x = list_3
h = 0.1358
n = 69
RK = 1/(2*sqrt(pi))
xkde = density(x, kernel='gaussian', bw=h)
upper = xkde$y + 1.96*sqrt((RK*xkde$y)/n*h)
lower = xkde$y - 1.96*sqrt((RK*xkde$y)/n*h)
plot(xkde)
lines(xkde$x, upper, lty=2, col='red')
lines(xkde$x, lower, lty=2, col='red')
```

```{r}


```



















