---
title: "Tut3"
author: "Zhu Xu<br>User ID:E0337988<br>Student ID:A0191344H"
date: "10 September 2018"
output:
  html_document:
    df_print: paged
  word_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
Q1:
```{r}
tut <- read.csv('C:/Users/MSI/Desktop/Notes/ST5210-Multivariate Data Analysis/Tutorial/salary.csv', header = T, sep = ",")
options(scipen = 10000, digits = 2)
colMeans(tut,2)
apply(tut,2,var)
```
Q2:
```{r}
pairs(tut)
pairs(tut[,c(1:6)])
```

Q3:
```{r}
cov(tut[2:17])
```

Q4:
```{r}
cov(tut[,c(2:9)], tut[,c(10:17)])
```

Q5:
```{r}
A <- tut[order(tut[,c("y")]),]
median(tut[,c("y")])
which(tut[,c("y")] < median(tut[,c("y")]))
low <- A[c(1:167),]
which(tut[,c("y")] > median(tut[,c("y")]))
high <- A[c(170:337),]
library(stats)
t.test(low[,c("x1")], high[,c("x1")],conf.level = 0.95)
t.test(low[,c("x2")], high[,c("x2")],conf.level = 0.95)
t.test(low[,c("x3")], high[,c("x3")],conf.level = 0.95)
t.test(low[,c("x4")], high[,c("x4")],conf.level = 0.95)
t.test(low[,c("x5")], high[,c("x5")],conf.level = 0.95)
t.test(low[,c("x6")], high[,c("x6")],conf.level = 0.95)
t.test(low[,c("x7")], high[,c("x7")],conf.level = 0.95)
t.test(low[,c("x8")], high[,c("x8")],conf.level = 0.95)
t.test(low[,c("x9")], high[,c("x9")],conf.level = 0.95)
t.test(low[,c("x10")], high[,c("x10")],conf.level = 0.95)
t.test(low[,c("x11")], high[,c("x11")],conf.level = 0.95)
t.test(low[,c("x12")], high[,c("x12")],conf.level = 0.95)
t.test(low[,c("x13")], high[,c("x13")],conf.level = 0.95)
t.test(low[,c("x14")], high[,c("x14")],conf.level = 0.95)
t.test(low[,c("x15")], high[,c("x15")],conf.level = 0.95)
t.test(low[,c("x16")], high[,c("x16")],conf.level = 0.95)
```
Q6:
```{r}
myfit <- lm(formula = y ~ x1+x2+x3+x4+x5+x6+x7+x8+x9+x10+x11+x12+x13+x14+x15+x16,data = tut)
myfit
summary(myfit)$r.square
summary(myfit)$adj.r.square
```
Q7:
```{r}
X <- tut[,2:17]
Z <- cov(X)
vector <- eigen(Z)$vector
value <- eigen(Z)$value
B <- vector[,1]
B
p <- as.numeric(as.matrix(tut[,1]))
q <- B %*% t(X)
q <- as.numeric(q)
cor(p,q)
```