---
title: '5226'
author: "Zhu Xu"
date: "2018Äê10ÔÂ12ÈÕ"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(sp)
data(meuse)
coordinates(meuse) <- c("x", "y")
plot(meuse, col="brown", cex=0.5)
title("Points")
###
data(meuse.riv)
meuse.lst <- list(Polygons(list(Polygon(meuse.riv)), "meuse.riv"))
meuse.pol <- SpatialPolygons(meuse.lst)
plot(meuse.pol, col="lightsteelblue")
title("Polygons")
###
data(meuse.grid)
coordinates(meuse.grid) <- c("x", "y")
meuse.grid <- as(meuse.grid, "SpatialPixels")
image(meuse.grid, col="khaki2")
title("Grid")
###
image(meuse.grid, col = "khaki2")
plot(meuse.pol, col = "lightsteelblue2", add = TRUE)
plot(meuse, add = TRUE, col = "brown", cex = .5)
###
image(meuse.grid, col = "khaki2")
plot(meuse.pol, add = TRUE, col = "lightsteelblue2")
plot(meuse, pch = 1, cex = sqrt(meuse$zinc)/20, add = TRUE)
legVals <- c(100, 200, 500, 1000, 2000)
legend("left", legend=legVals, pch = 1, pt.cex = sqrt(legVals)/20, bty = "o", title="measured, ppm", cex=0.8, y.inter=1.5)
title("measured and interpolated zinc")
###
library(RColorBrewer)
grys <- brewer.pal(7, "Reds")
meuse$lead.st = as.vector(scale(meuse$lead))
meuse$zinc.st = as.vector(scale(meuse$zinc))
meuse$copper.st = as.vector(scale(meuse$copper))
meuse$cadmium.st = as.vector(scale(meuse$cadmium))
cuts=c(-1.2,0,1,2,3,5)
print(spplot(meuse, c("cadmium.st", "copper.st", "lead.st", "zinc.st"), key.space="right", main = "standardised", layout=c(4,1), cex = .5, 
             cuts = cuts, col.regions=grys))
###
river <- list("sp.polygons", meuse.pol)
bank <- list("sp.polygons", meuse.grid, col="lightgray", alpha=0.2)
print(spplot(meuse, c("cadmium.st", "copper.st", "lead.st", "zinc.st"), key.space="right", main = "standardised", layout=c(4,1), sp.layout=list(river, bank), cex = .5, cuts = cuts, col.regions=grys))
###
river <- list("sp.polygons", meuse.pol, which=2)
print(spplot(meuse, c("cadmium.st", "copper.st", "lead.st", "zinc.st"), key.space="right", main = "standardised", layout=c(4,1), sp.layout=list(river, bank), cex = .5, cuts = cuts, col.regions=grys))
```

```{r}
rainbow(n=7)
col.out <- cm.colors(n=7)
print(spplot(meuse, "cadmium.st", key.space="right", main="standardised", sp.layout=river, cuts = cuts, col.regions=col.out))
rw.colors <- colorRampPalette(c("red", "blue"))
print(spplot(meuse, "cadmium.st", key.space="right", main="standardised", sp.layout=river, cuts = cuts, col.regions=rw.colors(7)))

```

```{r}
library(classInt)
q5 <- classIntervals(meuse$zinc, n=5, style="quantile")
q5
fj5 <- classIntervals(meuse$zinc, n=5, style="fisher")
fj5
pal <- brewer.pal(n=5, "Reds")
spplot(meuse, "zinc", cuts=q5$brks, col.regions=pal, key.space="left", main="Quantiles")
```

```{r}
library(rgdal)
library(spdep)
NY8 <- readOGR("C:/Users/MSI/Desktop/Notes/ST5226-Spatial Statistics/NY_data", "NY8_utm18")
pal <- brewer.pal(n=5, "Blues")
NY8$r <- NY8$TRACTCAS/NY8$POP8/5*1e+5
spplot(NY8, "r", col.regions=pal, at=classIntervals(NY8$r, n=5, "fisher")$brks, main="Unsoomthed Rates")
NY8$eb <- EBest(NY8$TRACTCAS, NY8$POP8)$estmm * 1e+5 /5
spplot(NY8, "eb", col.regions=pal, at=classIntervals(NY8$eb, n=5, "fisher")$brks, main="Emp.Bayes Smoother")
```

```{r}
choy <- choynowski(NY8$TRACTCAS, NY8$POP8)
id_less <- which(choy$pmap < 0.05 & choy$type == TRUE)
id_more <- which(choy$pmap < 0.05 & choy$type !=TRUE)
plot(NY8, axes=T)
plot(NY8[id_less, ], col="blue", border=NA, add=T)
plot(NY8[id_more, ], col="red", border=NA, add=T)
legend("topleft", legend=c("Obs. > Exp", "Obs. < Exp"), fill=c("red", "blue"))
```